-- CreateTable
CREATE TABLE `restaurants` (
    `id` INTEGER NOT NULL AUTO_INCREMENT,
    `name` VARCHAR(500) NULL,
    `type` VARCHAR(100) NULL,
    `phone` VARCHAR(50) NULL,
    `website` VARCHAR(500) NULL,
    `email` VARCHAR(255) NULL,
    `cuisine` VARCHAR(200) NULL,
    `street` VARCHAR(500) NULL,
    `housenumber` VARCHAR(50) NULL,
    `postcode` VARCHAR(20) NULL,
    `city` VARCHAR(255) NULL,
    `department` VARCHAR(255) NULL,
    `region` VARCHAR(255) NULL,
    `lat` DOUBLE NULL,
    `lon` DOUBLE NULL,
    `meta_osm_id` VARCHAR(100) NULL,
    `meta_osm_type` VARCHAR(50) NULL,
    `osm_id` VARCHAR(100) NULL,
    `osm_type` VARCHAR(50) NULL,
    `opening_hours` TEXT NULL,
    `wheelchair` VARCHAR(20) NULL,
    `delivery` VARCHAR(20) NULL,
    `takeaway` VARCHAR(20) NULL,
    `outdoor_seating` VARCHAR(20) NULL,
    `last_update` DATETIME(3) NULL DEFAULT CURRENT_TIMESTAMP(3),
    `created_at` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),

    UNIQUE INDEX `restaurants_meta_osm_id_key`(`meta_osm_id`),
    INDEX `restaurants_type_idx`(`type`),
    INDEX `restaurants_region_idx`(`region`),
    INDEX `restaurants_department_idx`(`department`),
    INDEX `restaurants_city_idx`(`city`),
    INDEX `restaurants_name_idx`(`name`),
    PRIMARY KEY (`id`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
